- name: Install kubectl on linux
  import_tasks: linux.yml
  when: ansible_distribution == "Ubuntu"

- name: Install kubectl on MacOS
  community.general.homebrew:
    name: kubectl
    state: present
  when: ansible_distribution == "MacOSX"
