- name: Install tmux
  become: true
  ansible.builtin.package:
    state: present
    name: tmux

- name: Checkout TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
