---
- name: Install nvim in Linux
  import_tasks: linux.yml
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Fedora"

- name: Install nvim in macOS
  import_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- name: Generate :help pages
  shell: nvim --headless -c 'helptags ALL' -c quit

- name: Install Treesitter parsers
  shell: nvim --headless -c 'TSUpdateSync' -c quit
