---
# tasks file for oh_my_zsh
- name: Install Git
  become: true
  ansible.builtin.package:
    state: present
    name: git
 
- name: Install ZSH
  become: true
  ansible.builtin.package:
    name: zsh
    state: present
 
- name: Override powerline fonts package name for Debian.
  ansible.builtin.set_fact:
    powerlinefonts: fonts-powerline
  when: ansible_os_family == 'Debian'
 
- name: Override fd-find package name for Archlinux.
  ansible.builtin.set_fact:
    fdfind: fd
  when: ansible_os_family == 'Archlinux'
 
- name: Install Powerline fonts
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ powerlinefonts }}"
 
- name: Install ripgrep
  become: true
  ansible.builtin.package:
    state: present
    name: ripgrep
 
- name: Install procs in Arch/Fedora
  become: true
  ansible.builtin.package:
    state: present
    name: procs
  when: ansible_os_family != 'Debian'
 
# unzip is useful for extracting zips
- name: Install unzip
  become: true
  ansible.builtin.package:
    state: present
    name: unzip
 
- name: Install Google Noto emoji fonts
  become: true
  ansible.builtin.package:
    state: present
    name: noto-fonts-emoji
  when: ansible_os_family == 'Archlinux'
 
# To get "icons" in exa output
- name: Install Patched font Arimo from nerd-fonts (Arch)
  become: true
  ansible.builtin.package:
    state: present
    name: ttf-arimo-nerd
  when: ansible_os_family == 'Archlinux'
 
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1
 
- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
 
- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1
 
- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
 
- name: Change user shell to zsh 
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
